[package]
name = "aoc2020_rust"
version = "0.1.0"
authors = ["GitHub <noreply@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]

[[bin]]
name = "day1"
path = "src/bin/day_1.rs"